### PR TITLE
Ericr 7k2

### PR DESCRIPTION
**Pull request by ericrqs**
add 7k support and error checking

### CODE REVIEW

**Comment by ericrqs** [comment]
Note: Devin Thorne was really Eric Rosenquist on the customer's computer

**Comment by Costya-Y** [comment]
Hi, Eric, could you please also remove .idea files from the request?

**Comment by Costya-Y** [comment]
Also please remove or add to gitignore "build", "dist" and "release" folders.

**Comment by yaroslavNqualisystems** [comment]
Remove and then add to gitignore all this files, easier.

**Pull request merged**
